In [1]:
import numpy as np

# 数据类型

- 标量 Scalar
- 向量 Vector
- 矩阵 Martrix
- 张量 Tensor

# 矩阵运算基础

- 矩阵转置
- 对陈矩阵：沿着对角线，两侧数据对称的矩阵
- 对角矩阵：除对角线外其他项都是0的矩阵
- 单位矩阵：对角线都为1的矩阵

## 构造对角矩阵

In [5]:
# 构造对角矩阵
v = np.array([1, 8, 4])
np.diag(v)

array([[1, 0, 0],
       [0, 8, 0],
       [0, 0, 4]])

## 构造单位矩阵

In [6]:
# 构造单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 阿达码积：两个矩阵对应位置上的元素相乘

In [21]:
print("-"*20)
a = np.array(range(4)).reshape(2, 2)
print(a)

print("-"*20)
b = np.array(range(4, 8)).reshape(2, 2)
print(b)

print("-"*10, "阿达码积", "-"*10)
print(a*b)

--------------------
[[0 1]
 [2 3]]
--------------------
[[4 5]
 [6 7]]
---------- 阿达码积 ----------
[[ 0  5]
 [12 21]]


## 点积

In [13]:
# 使用 np.dot 方法做点积运算
np.dot(a, b)

array([[ 6,  7],
       [26, 31]])

In [15]:
# 也可以先将数组转为矩阵，再使用*做点积运算
np.asmatrix(a) * np.asmatrix(b)

matrix([[ 6,  7],
        [26, 31]])

## 对角矩阵操作

### 对角矩阵与向量互转

`linalg`是`linear algebra`的缩写，直译为线性代数。在NumPy库中，`numpy.linalg`模块提供了许多线性代数的函数，如求解线性方程组、计算行列式、计算矩阵的秩、计算矩阵的特征值和特征向量等。因此，`linalg`的命名代表了这个模块的功能。

In [18]:
import numpy as np

# 从向量到对角矩阵
a = np.diag([1, 2, 3])
print(a)
# 从对角矩阵到向量
print("-"*20)
v, e = np.linalg.eig(a)
print(v)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
--------------------
[1. 2. 3.]


### 对角矩阵幂等运算等于对角线上各值的幂运算

In [24]:
# 4种方法实现对角矩阵3次方
print("-"*10, "阿达码积", "-"*10)
print(a*a*a)

print("-"*20)
print(a**3)

print("-"*20)
print((a**2)*a)

print("-"*10, "对角矩阵的点积与阿达码积相同", "-"*10)
print(a@a@a)

---------- 阿达码积 ----------
[[ 0  1]
 [ 8 27]]
--------------------
[[ 0  1]
 [ 8 27]]
--------------------
[[ 0  1]
 [ 8 27]]
---------- 对角矩阵的点积与阿达码积相同 ----------
[[ 6 11]
 [22 39]]


### 对角矩阵求逆

In [30]:
print("-"*10, "np.linalg.inv对二维数组求逆", "-"*10)
print(np.linalg.inv(a))

print("-"*10, "转换为矩阵后，使用I操作求逆", "-"*10)
print(np.matrix(a).I)

---------- np.linalg.inv对二维数组求逆 ----------
[[-1.5  0.5]
 [ 1.   0. ]]
---------- 转换为矩阵后，使用I操作求逆 ----------
[[-1.5  0.5]
 [ 1.   0. ]]


In [26]:
np.linalg.inv(a) @ a

array([[1., 0.],
       [0., 1.]])

### 对角矩阵左乘其他矩阵：等价于对应行乘对角元素

In [39]:
a = np.diag([1, 2, 3])
b = np.array([
    [4, 5, 6],
    [3, 2, 1],
    [2, 2, 2]
])
print(a @ b)

[[4 5 6]
 [6 4 2]
 [6 6 6]]


### 对角矩阵又乘其他矩阵：等价于对应列乘对角元素

In [41]:
a = np.diag([1, 2, 3])
b = np.array([
    [4, 5, 6],
    [3, 2, 1],
    [2, 2, 2]
])
print(b @ a)

[[ 4 10 18]
 [ 3  4  3]
 [ 2  4  6]]
