# PyTorch中的张量

## 定义张量

- 将已有数值转换为张量
- 根据指定形状、类型生成张量
- 根据指定形状生成固定值的张量

### 从数值转换张量

In [2]:
import torch
import numpy as np

# 从标量
print(torch.tensor(5))

# 从数组
b = np.asarray([4, 5, 6])
print(torch.tensor(b))

tensor(5)
tensor([4, 5, 6])


### 根据形状和类型生成张量

In [4]:
# 默认输出类型：torch.float32
import torch
print(torch.get_default_dtype())
print(torch.Tensor([1, 3]).dtype)

torch.float32
torch.float32


In [9]:
# 修改默认输出
torch.set_default_dtype(torch.float64)
print(torch.get_default_dtype())
print(torch.Tensor([1, 3]).dtype)

torch.float64
torch.float64


In [10]:
# 指定张量的形状
print(torch.Tensor(2))
print(torch.Tensor(1, 2))
print(torch.Tensor([2]))
print(torch.Tensor([1, 2]))

tensor([0., 0.])
tensor([[0., 0.]])
tensor([2.])
tensor([1., 2.])


In [11]:
# 用随机数填充
torch.rand(2, 3)

tensor([[0.1996, 0.3047, 0.4350],
        [0.0988, 0.4774, 0.0239]])

### 根据形状生成固定值的张量

- torch.ones() 值为1
- torch.zeros() 值为0
- torch.ones_like() 与目标张量形状相同、值为1
- torch.zeros_like() 与目标张量形状相同、值为0
- torch.randn() 随机数
- torch.eye() 生成对角矩阵
- torch.full() 所有元素为指定值

In [15]:
import torch

# 创建一个形状为(3, 3)的张量，所有元素都为1
ones = torch.ones((3, 3))
print("ones:\n", ones)

# 创建一个形状为(3, 3)的张量，所有元素都为0
zeros = torch.zeros((3, 3))
print("zeros:\n", zeros)

# 创建一个与ones形状相同的张量，所有元素都为1
ones_like = torch.ones_like(ones)
print("ones_like:\n", ones_like)

# 创建一个与zeros形状相同的张量，所有元素都为0
zeros_like = torch.zeros_like(zeros)
print("zeros_like:\n", zeros_like)

# 创建一个形状为(3, 3)的张量，所有元素都是从标准正态分布中随机采样的
randn = torch.randn((3, 3))
print("randn:\n", randn)

# 创建一个形状为(3, 3)的单位矩阵
eye = torch.eye(3)
print("eye:\n", eye)

# 创建一个形状为(3, 3)的张量，所有元素都为7
full = torch.full((3, 3), 7)
print("full:\n", full)

ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
ones_like:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
zeros_like:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
randn:
 tensor([[ 1.3156, -0.0499,  0.1282],
        [-1.6348, -0.3369, -1.5173],
        [-1.4882,  0.3605,  0.4127]])
eye:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
full:
 tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])


## 生成随机张量

### 设置随机种子

In [20]:
torch.initial_seed()

2

In [19]:
torch.manual_seed(2)
torch.initial_seed()

2

### 指定形状生成随机值

In [21]:
torch.randn(2, 3)

tensor([[ 0.3923, -0.2236, -0.3195],
        [-1.2050,  1.0445, -0.6332]])

### 生成线性空间的随机值

In [27]:
# 按照步长为2进行取值
print(torch.arange(1, 10, step=4))

# 均匀取出5个值
print(torch.linspace(1, 10, steps=4))

tensor([1, 5, 9])
tensor([ 1.,  4.,  7., 10.])


### 生成对数空间的随机值

In [29]:
print(torch.logspace(1, 10, steps=5))

tensor([1.0000e+01, 1.7783e+03, 3.1623e+05, 5.6234e+07, 1.0000e+10])


### 生成未初始化的矩阵

In [30]:
print(torch.empty(1, 2))

tensor([[0., 0.]])


### 更多的随机值生成函数

- bernouli() 伯努力分布
- cauchy() 柯西分布
- exponential() 指数分布
- geometric() 几何分布

## 张量的基本操作

### 获得张量中元素的个数

In [31]:
import torch
a = torch.Tensor(2)
print(torch.numel(a))

2


### 张量的判断

In [32]:
a = torch.Tensor(2)
print(torch.is_tensor(a))

True


### 张量的类型转换

In [33]:
a = torch.FloatTensor([4])
print(a.type(torch.IntTensor))

tensor([4], dtype=torch.int32)


## 在CPU和GPU控制的内存中定义张量

## 张量间的数据操作