In [4]:
from matplotlib import pyplot as plt
import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.set_printoptions(edgeitems=2)
torch.manual_seed(123)

# 从张量开始

## 张量定义和索引

In [12]:
# 初始化张量
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [7]:
a.to(device="cuda")

tensor([1., 1., 1.], device='cuda:0')

In [13]:
# 初始化多维张量
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [14]:
# 索引张量
some_list = list(range(6))

In [22]:
# 所有
some_list[:]

[0, 1, 2, 3, 4, 5]

In [21]:
# 从第1个到第4个
some_list[1:4]

[1, 2, 3]

In [20]:
# 从第1个到最后
some_list[1:]

[1, 2, 3, 4, 5]

In [19]:
# 从第1个移动到第4个，步长为2
some_list[1:4:2]

[1, 3]

In [24]:
a.shape

torch.Size([3])

In [30]:
a.untyped_storage()

 0
 0
 128
 63
 0
 0
 128
 63
 0
 0
 128
 63
[torch.storage.UntypedStorage(device=cpu) of size 12]

In [28]:
b = a.to(device="cuda")

In [29]:
b.untyped_storage()

 0
 0
 128
 63
 0
 0
 128
 63
 0
 0
 128
 63
[torch.storage.UntypedStorage(device=cuda:0) of size 12]

In [55]:
# 多维张量
points = torch.tensor([[4.0, 1.0], [5.0, 2.0], [6.0, 8.0]]).to(device="cuda")
points

tensor([[4., 1.],
        [5., 2.],
        [6., 8.]], device='cuda:0')

In [47]:
# 转置
points_t = points.t()
points_t

tensor([[4., 5., 6.],
        [1., 2., 8.]], device='cuda:0')

In [54]:
# 与numpy互操作
points.to(device="cpu").numpy()

array([[4., 1.],
       [5., 2.],
       [6., 8.]], dtype=float32)