# PyTorch中的张量

## 定义张量

- 将已有数值转换为张量
- 根据指定形状、类型生成张量
- 根据指定形状生成固定值的张量

### 从数值转换张量

In [1]:
import torch
import numpy as np

# 从标量
print(torch.tensor(5))

# 从数组
b = np.asarray([4, 5, 6])
print(torch.tensor(b))

tensor(5)
tensor([4, 5, 6])


### 根据形状和类型生成张量

In [2]:
# 默认输出类型：torch.float32
import torch
print(torch.get_default_dtype())
print(torch.Tensor([1, 3]).dtype)

torch.float32
torch.float32


In [3]:
# 修改默认输出
torch.set_default_dtype(torch.float64)
print(torch.get_default_dtype())
print(torch.Tensor([1, 3]).dtype)

torch.float64
torch.float64


In [4]:
# 指定张量的形状
print(torch.Tensor(2))
print(torch.Tensor(1, 2))
print(torch.Tensor([2]))
print(torch.Tensor([1, 2]))

tensor([6.9447e-310, 6.9447e-310])
tensor([[6.9447e-310, 6.0577e-316]])
tensor([2.])
tensor([1., 2.])


In [5]:
# 用随机数填充
torch.rand(2, 3)

tensor([[0.9661, 0.9740, 0.4645],
        [0.4900, 0.7924, 0.8380]])

### 根据形状生成固定值的张量

- torch.ones() 值为1
- torch.zeros() 值为0
- torch.ones_like() 与目标张量形状相同、值为1
- torch.zeros_like() 与目标张量形状相同、值为0
- torch.randn() 随机数
- torch.eye() 生成对角矩阵
- torch.full() 所有元素为指定值

In [6]:
import torch

# 创建一个形状为(3, 3)的张量，所有元素都为1
ones = torch.ones((3, 3))
print("ones:\n", ones)

# 创建一个形状为(3, 3)的张量，所有元素都为0
zeros = torch.zeros((3, 3))
print("zeros:\n", zeros)

# 创建一个与ones形状相同的张量，所有元素都为1
ones_like = torch.ones_like(ones)
print("ones_like:\n", ones_like)

# 创建一个与zeros形状相同的张量，所有元素都为0
zeros_like = torch.zeros_like(zeros)
print("zeros_like:\n", zeros_like)

# 创建一个形状为(3, 3)的张量，所有元素都是从标准正态分布中随机采样的
randn = torch.randn((3, 3))
print("randn:\n", randn)

# 创建一个形状为(3, 3)的单位矩阵
eye = torch.eye(3)
print("eye:\n", eye)

# 创建一个形状为(3, 3)的张量，所有元素都为7
full = torch.full((3, 3), 7)
print("full:\n", full)

ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
ones_like:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
zeros_like:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
randn:
 tensor([[ 2.0313,  0.3689, -0.4313],
        [ 0.0216, -1.9894,  0.8077],
        [-0.2210,  1.0119,  0.1432]])
eye:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
full:
 tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])


## 生成随机张量

### 设置随机种子

In [7]:
torch.initial_seed()

9782425656273393658

In [19]:
torch.manual_seed(2)
torch.initial_seed()

2

### 指定形状生成随机值

In [9]:
torch.randn(2, 3)

tensor([[ 0.6046,  0.1257,  0.7042],
        [-3.2458, -0.7085, -1.7238]])

### 生成线性空间的随机值

In [10]:
# 按照步长为2进行取值
print(torch.arange(1, 10, step=4))

# 均匀取出5个值
print(torch.linspace(1, 10, steps=4))

tensor([1, 5, 9])
tensor([ 1.,  4.,  7., 10.])


### 生成对数空间的随机值

In [11]:
print(torch.logspace(1, 10, steps=5))

tensor([1.0000e+01, 1.7783e+03, 3.1623e+05, 5.6234e+07, 1.0000e+10])


### 生成未初始化的矩阵

In [30]:
print(torch.empty(1, 2))

tensor([[0., 0.]])


### 更多的随机值生成函数

- bernouli() 伯努力分布
- cauchy() 柯西分布
- exponential() 指数分布
- geometric() 几何分布

## 张量的基本操作

### 获得张量中元素的个数

In [31]:
import torch
a = torch.Tensor(2)
print(torch.numel(a))

2


### 张量的判断

In [32]:
a = torch.Tensor(2)
print(torch.is_tensor(a))

True


### 张量的类型转换

In [34]:
# 使用type()方法转换类型
a = torch.FloatTensor([4])
print(a.type(torch.IntTensor))

tensor([4], dtype=torch.int32)


In [36]:
# 也可以按如下方式写
print(a.int())
print(a.double())

tensor([4], dtype=torch.int32)
tensor([4.])


### 重载操作符函数

In [2]:
a = torch.FloatTensor([4])
print(a)
b = torch.add(a, a)
print(b)

tensor([4.])
tensor([8.])


In [3]:
torch.add(a, a, out=b)
print(b)

tensor([8.])


PyTorch重载了许多Python的操作符，可以直接在张量上使用这些操作符：

1. **算术操作符**：`+`（加法）、`-`（减法）、`*`（乘法）、`/`（除法）、`//`（整除）、`%`（取余）、`**`（幂运算）。

2. **比较操作符**：`>`（大于）、`<`（小于）、`>=`（大于等于）、`<=`（小于等于）、`==`（等于）、`!=`（不等于）。

3. **逻辑操作符**：`&`（逻辑与）、`|`（逻辑或）、`^`（逻辑异或）、`~`（逻辑非）。

4. **位移操作符**：`>>`（右移）、`<<`（左移）。

5. **矩阵乘法操作符**：`@`。

这些操作符都是元素级别的，也就是说，它们会对两个张量的对应元素进行操作。例如，`a + b`会返回一个新的张量，这个张量的每个元素都是`a`和`b`的对应元素的和。

此外，PyTorch还重载了一些Python的内置函数，如`abs`、`len`、`str`、`float`等。

In [4]:
a + a

tensor([8.])

### 自变化运算函数

In [6]:
# 原地修改
a.add_(b)
print(a)

tensor([20.])


### 更多数学运算

In [7]:
print(a.mean())
print(a.sqrt())

tensor(20.)
tensor([4.4721])


### 张量与Numpy间的相互转换

In [8]:
import numpy as np
a = torch.FloatTensor([4])
print(a.numpy())

[4.]


In [10]:
# numpy -> torch
b = np.asarray([4])
print(torch.from_numpy(b))
print(torch.tensor(b))

tensor([4])
tensor([4])


### 形状获取

In [18]:
print("-"*10, "pytorch", "-"*10)
x = torch.rand(2, 2)
print(x.shape, x.size())

print("-"*10, "numpy", "-"*10)
y = np.asarray([[4, 5], [5, 4]])
print(y.shape, y.size)

---------- pytorch ----------
torch.Size([2, 2]) torch.Size([2, 2])
---------- numpy ----------
(2, 2) 4


### 切片：与bumpy几乎一致

In [19]:
x = torch.rand(2, 1)
print(x[:])

y = np.asarray([4, 2])
print(y[:])

tensor([[0.4579],
        [0.5331]])
[4 2]


### 张量与Numpy相互转换的陷阱

- 将Numpy转换为PyTorch张量时，按照读时引用、写时复制的机制
- 将PyTorch张量转换为Numpy时，按照读时引用、写时原地修改的机制（**注意，这可能是一个陷阱**）

In [22]:
y = np.array([1, 1])
x = torch.from_numpy(y)
print(x) # 输出为 tensor([1, 1])

y += 1
print(x) # 输出为 tensor([2, 2])
print(y) # 输出为 [2 2]

tensor([1, 1])
tensor([2, 2])
[2 2]


## 在CPU和GPU控制的内存中定义张量

### CPU -> GPU

In [ ]:
import torch
a = torch.FloatTensor([4])
b = a.cuda()
print(b)

In [ ]:
print(b.cpu())

### 直接在 GPU 中定义

In [ ]:
a = torch.tensor([4], device="cuda")
print(a)

### 使用 to() 方法指定设备

In [ ]:
a = torch.FloatTensor([4])
print(a)
print(a.to("cuda:0"))

### 使用 CUDA_VISIBLE_DEVICES 来指定设备

使用 `python_dotenv` 管理环境变量，或使用下面的脚本：
```shell
CUDA_VISIBLE_DEVICES=0 python mytask.py
```

## 张量间的数据操作

### reshape()

In [26]:
a = torch.tensor([[1, 2], [3, 4]])
print(torch.reshape(a, (1, -1))) # -1 被自动转换为4，因为 2x2 = 1x4

tensor([[1, 2, 3, 4]])


In [29]:
# -1 代表该维度由系统自动计算
print(a.reshape((1, -1)))
print(a.view((1, -1)))

tensor([[1, 2, 3, 4]])
tensor([[1, 2, 3, 4]])


### squeeze() / unsqueeze()

In [43]:
# 构造 2x2 的矩阵
a = torch.tensor([[1, 2], [3, 4]])
print(a.shape)
# 变换为 1x4 的矩阵
b = torch.reshape(a, (1, -1))
print(b.shape)

torch.Size([2, 2])
torch.Size([1, 4])


In [44]:
# 减少一个大小为1的维度
print(torch.squeeze(b).shape)

torch.Size([4])


In [45]:
# 增加一个大小为1的维度
print(torch.unsqueeze(b, 1).shape)

torch.Size([1, 1, 4])


### t() / transpose() 矩阵转置

In [50]:
b = torch.tensor([[5, 6, 7], [2, 8, 0]])
print(b.shape)

# 用 t() 转置
print(torch.t(b).shape)
# 用 transpose() 转置
print(torch.transpose(b, dim0=1, dim1=0).shape)

torch.Size([2, 3])
torch.Size([3, 2])
torch.Size([3, 2])


### permute() 交换维度

In [51]:
# 也可以用于实现矩阵转置
b.permute(1, 0)

tensor([[5, 2],
        [6, 8],
        [7, 0]])

In [65]:
# 不过，更多用于任意的维度交换
x = torch.randn(1, 2, 3)
print(x.shape)
print(x.permute(1, 2, 0).shape)

torch.Size([1, 2, 3])
torch.Size([2, 3, 1])


### view() / contiguous()

In [77]:
# 创建一个形状为(4, 4)的张量
x = torch.randn(4, 4)
print("x:\n", x)

# 使用view函数改变张量的形状
y = x.view(2, 2, 4)
print("y:\n", y)

# 使用view函数改变张量的形状
z = x.view(-1, 8)  # -1表示该维度的大小由其他维度决定
print("z:\n", z)

# 使用view函数获取张量的元素数量
num_elements = x.view(-1).size(0)
print("Number of elements:", num_elements)

x:
 tensor([[ 1.5474,  0.4929,  0.6593, -1.9054],
        [ 1.9615,  1.1072, -1.0313, -0.7408],
        [ 1.5718,  1.1386, -0.2428, -0.6373],
        [ 1.5705,  1.1780,  0.1223, -0.5077]])
y:
 tensor([[[ 1.5474,  0.4929,  0.6593, -1.9054],
         [ 1.9615,  1.1072, -1.0313, -0.7408]],

        [[ 1.5718,  1.1386, -0.2428, -0.6373],
         [ 1.5705,  1.1780,  0.1223, -0.5077]]])
z:
 tensor([[ 1.5474,  0.4929,  0.6593, -1.9054,  1.9615,  1.1072, -1.0313, -0.7408],
        [ 1.5718,  1.1386, -0.2428, -0.6373,  1.5705,  1.1780,  0.1223, -0.5077]])
Number of elements: 16


**注意：view() 方法要求内存连续，无法处理已经应用过t()、transpose()、permute()等方法的张量**

因此，view()有时需要与contiguous()一起搭配使用。

In [79]:
# 定义一个张量后，默认为连续内存
print(x.is_contiguous())
print(x.view(-1, 2).shape)

c = x.t()
# 转置过
print(c.is_contiguous())

# 重新处理为连续内存
print(c.contiguous().is_contiguous())
print(c.contiguous().view(-1).shape)

True
torch.Size([8, 2])
False
True
torch.Size([16])


### cat() 连接数据

In [81]:
a = torch.tensor([
    [1, 2],
    [3, 4]
])

b = torch.tensor([
    [5, 6],
    [7, 8]
])

print(torch.cat([a, b], dim=0))
print(torch.cat([a, b], dim=1))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


### chunk() 分割数据

In [88]:
a = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8],
])

# 沿着第 0 维度拆分为 2 个chunks
print(torch.chunk(a, chunks=2, dim=0))
# 沿着第 1 维度拆分为 2 个chunks
print(torch.chunk(a, chunks=2, dim=1))

(tensor([[1, 2],
        [3, 4]]), tensor([[5, 6],
        [7, 8]]))
(tensor([[1],
        [3],
        [5],
        [7]]), tensor([[2],
        [4],
        [6],
        [8]]))


### split() 分割数据

In [90]:
b = torch.tensor([[5, 6, 7], [2, 8, 0]])

# 沿着第 1 个维度，按照 split_size_or_sections 指定的形状拆分，拆分的余数被保留为最后一部份
torch.split(b, split_size_or_sections=(1, 2), dim=1)

(tensor([[5],
         [2]]),
 tensor([[6, 7],
         [8, 0]]))

### gather() 提取数据

In [92]:
b = torch.tensor([
    [5, 6, 7],
    [2, 8, 0]
])

print(torch.gather(b, dim=1, index=torch.tensor([[1, 0], [1, 2]])))
print(torch.gather(b, dim=1, index=torch.tensor([[1, 0, 0]])))

tensor([[6, 5],
        [8, 0]])
tensor([[6, 5, 5]])


### select() 过滤数据

In [94]:
# 使用 index_select 选择维度
torch.index_select(b, dim=0, index=torch.tensor(1))

tensor([[2, 8, 0]])

In [97]:
# ge -> 大于等于, greater-equal
torch.masked_select(b, b.ge(6))

tensor([6, 7, 8])

In [100]:
# b.ge(6) 等价于 b >= 6
torch.masked_select(b, b >= 6)

tensor([6, 7, 8])

### nonzero() 找出非0值位置索引

In [112]:
eye = torch.eye(3)
print(eye)

# 找出非0的位置索引
print(torch.nonzero(eye))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[0, 0],
        [1, 1],
        [2, 2]])


### where() 根据条件取值

In [129]:
# 创建两个形状为(3, 3)的随机整数张量
torch.manual_seed(0)

x = torch.randint(low=0, high=10, size=(3, 3))
y = torch.randint(low=10, high=20, size=(3, 3))
print("x:\n", x)
print("y:\n", y)

# 创建一个条件
condition = x >= 5

# 使用torch.where函数过滤
# 优先选择x中的满足contidion的元素，否则就使用y中的元素
z = torch.where(condition, x, y)
print("z:\n", z)

x:
 tensor([[4, 9, 3],
        [0, 3, 9],
        [7, 3, 7]])
y:
 tensor([[13, 11, 16],
        [16, 19, 18],
        [16, 16, 18]])
z:
 tensor([[13,  9, 16],
        [16, 19,  9],
        [ 7, 16,  7]])


### clamp() 根据阈值截断

In [132]:
# 超出阈值的元素替换为min或max指定的值
torch.clamp(x, min=2, max=5)

tensor([[4, 5, 3],
        [2, 3, 5],
        [5, 3, 5]])

### argmax() / argmin() 最大值、最小值的位置索引

In [157]:
# 如果不指定维度，就当作1维来寻找
x = torch.tensor([
    [7, 5, 6],
    [9, 3, 8]
])

In [158]:
print(torch.argmax(x))

# 等同于
print(torch.argmax(x.view(-1)))

tensor(3)
tensor(3)


In [159]:
# 沿着第0维寻找最大值
torch.argmax(x, dim=0)

tensor([1, 0, 1])